Player.create({name: "Odell Beckham Jr", position: "WR", positional_ranking: 1, pic: "http://www.rotoworld.com/images/headshots/NFL/9403.jpg"})
Player.create({name: "Mike Evans", position: "WR", positional_ranking: 2, pic: "http://www.rotoworld.com/images/headshots/NFL/9296.jpg"})
Player.create({name: "Antonio Brown", position: "WR", positional_ranking: 3, pic: "http://www.rotoworld.com/images/headshots/NFL/5698.jpg"})
Player.create({name: "Julio Jones", position: "WR", positional_ranking: 4, pic: "http://www.rotoworld.com/images/headshots/NFL/6475.jpg"})
Player.create({name: "Amari Cooper", position: "WR", positional_ranking: 5, pic: "http://www.rotoworld.com/images/headshots/NFL/10310.jpg"})
Player.create({name: "Allen Robinson", position: "WR", positional_ranking: 6, pic: "http://www.rotoworld.com/images/headshots/NFL/9297.jpg"})
Player.create({name: "DeAndre Hopkins", position: "WR", positional_ranking: 7, pic: "http://www.rotoworld.com/images/headshots/NFL/8404.jpg"})
Player.create({name: "AJ Green", position: "WR", positional_ranking: 8, pic: "http://www.rotoworld.com/images/headshots/NFL/6438.jpg"})
Player.create({name: "TY Hilton", position: "WR", positional_ranking: 9, pic: "http://www.rotoworld.com/images/headshots/NFL/7558.jpg"})
Player.create({name: "Michael Thomas", position: "WR", positional_ranking: 10, pic: "http://www.rotoworld.com/images/headshots/NFL/11222.jpg"})

Player.create({name: "Ezekiel Elliott", position: "RB", positional_ranking: 1, pic: "http://www.rotoworld.com/images/headshots/NFL/11265.jpg"})
Player.create({name: "LeVeon Bell", position: "RB", positional_ranking: 2, pic: "http://www.rotoworld.com/images/headshots/NFL/8390.jpg"})
Player.create({name: "David Johnson", position: "RB", positional_ranking: 3, pic: "http://www.rotoworld.com/images/headshots/NFL/10404.jpg"})
Player.create({name: "Devonta Freeman", position: "RB", positional_ranking: 4, pic: "http://www.rotoworld.com/images/headshots/NFL/9423.jpg"})
Player.create({name: "Jordan Howard", position: "RB", positional_ranking: 5, pic: "http://www.rotoworld.com/images/headshots/NFL/11339.jpg"})
Player.create({name: "Todd Gurley", position: "RB", positional_ranking: 6, pic: "http://www.rotoworld.com/images/headshots/NFL/10288.jpg"})
Player.create({name: "Leonard Fournette", position: "RB", positional_ranking: 6, pic: "http://www.rotoworld.com/images/headshots/NFL/12132.jpg"})
Player.create({name: "Jay Ajayi", position: "RB", positional_ranking: 7, pic: "http://www.rotoworld.com/images/headshots/NFL/10361.jpg"})
Player.create({name: "Isaiah Crowell", position: "RB", positional_ranking: 8, pic: "http://www.rotoworld.com/images/headshots/NFL/9401.jpg"})
Player.create({name: "Carlos Hyde", position: "RB", positional_ranking: 9, pic: "http://www.rotoworld.com/images/headshots/NFL/9381.jpg"})
Player.create({name: "Lamar Miller", position: "RB", positional_ranking: 10, pic: "http://www.rotoworld.com/images/headshots/NFL/7408.jpg"})
