Player.create({name: "Odell Beckham Jr", position: "WR", positional_ranking: 1})
Player.create({name: "Mike Evans", position: "WR", positional_ranking: 2})
Player.create({name: "Antonio Brown", position: "WR", positional_ranking: 3})
Player.create({name: "Julio Jones", position: "WR", positional_ranking: 4})
Player.create({name: "Amari Cooper", position: "WR", positional_ranking: 5})
Player.create({name: "Allen Robinson", position: "WR", positional_ranking: 6})
Player.create({name: "DeAndre Hopkins", position: "WR", positional_ranking: 7})
Player.create({name: "AJ Green", position: "WR", positional_ranking: 8})
Player.create({name: "TY Hilton", position: "WR", positional_ranking: 9})
Player.create({name: "Michael Thomas", position: "WR", positional_ranking: 10})

Player.create({name: "Ezekiel Elliot", position: "RB", positional_ranking: 1})
Player.create({name: "LeVeon Bell", position: "RB", positional_ranking: 2})
Player.create({name: "David Johnson", position: "RB", positional_ranking: 3})
Player.create({name: "Devonta Freeman", position: "RB", positional_ranking: 4})
Player.create({name: "Jordan Howard", position: "RB", positional_ranking: 5})
Player.create({name: "Todd Gurley", position: "RB", positional_ranking: 6})
Player.create({name: "Leonard Fournette", position: "RB", positional_ranking: 6})
Player.create({name: "Jay Ajayi", position: "RB", positional_ranking: 7})
Player.create({name: "Isaiah Crowell", position: "RB", positional_ranking: 8})
Player.create({name: "Carlos Hyde", position: "RB", positional_ranking: 9})
Player.create({name: "Lamar Miller", position: "RB", positional_ranking: 10})
