Player.create({name: "Odell Beckham Jr", position: "WR", rating: 9})
Player.create({name: "Sammy Watkins", position: "WR", rating: 10})
Player.create({name: "Julio Jones", position: "WR", rating: 10})
Player.create({name: "Kelvin Benjamin", position: "WR", rating: 8})
Player.create({name: "Brandin Cooks", position: "WR", rating: 8})

Player.create({name: "David Johnson", position: "RB", rating: 9})
Player.create({name: "Devonta Freeman", position: "RB", rating: 9})
Player.create({name: "LeVeon Bell", position: "RB", rating: 9})
Player.create({name: "Ezekiel Elliot", position: "RB", rating: 10})
Player.create({name: "Isaiah Crowell", position: "RB", rating: 8})
